###############################################
# Common Keys for all apps
###############################################

x-common-keys: &common-keys
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    dns:
      - 1.1.1.1
      - 1.0.0.1

services:
###############################################
# RADARR - Movies
###############################################
  radarr:
    <<: *common-keys
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    ports:
      - 7878:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /mnt/data:/mnt/data

###############################################
# SONARR - TV Shows
###############################################

  sonarr:
    <<: *common-keys
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /mnt/data:/mnt/data

###############################################
# LIDARR - Music
###############################################

  lidarr:
    <<: *common-keys
    container_name: lidarr
    image: ghcr.io/hotio/lidarr:latest
    ports:
      - 8686:8686
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/lidarr:/config
      - /mnt/data:/mnt/data

###############################################
# BAZARR - Subtitles
###############################################

  bazarr:
    <<: *common-keys
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    ports:
      - 6767:6767
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /mnt/data/media:/mnt/data/media

###############################################
# PROWLARR - Indexer Manager
###############################################

  prowlarr:
    <<: *common-keys
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    ports:
      - 9696:9696
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/prowlarr:/config

###############################################
# SABnzbd - Downloader
###############################################

  sabnzbd:
    <<: *common-keys	
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    logging:
      driver: json-file
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sabnzbd:/config
      - /mnt/data/usenet:/mnt/data/usenet:rw

###############################################
# JELLYFIN - Media Server
###############################################

  jellyfin:
    <<: *common-keys
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/jellyfin:/config
      - /mnt/data/media:/mnt/data/media:ro #read-only
    ports:
      - 8096:8096


###############################################
#SEERR - Request Management (Jellyseerr)
###############################################

  seerr:
    <<: *common-keys
    container_name: seerr
    image: ghcr.io/seerr-team/seerr:latest
    ports:
      - 5055:5055
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/seerr:/app/config

###############################################
# ARR Stack Dedicated Network
###############################################

networks:
  default:
    name: arr_network

###############################################
###############################################